version: "3.8"

services:
  frontend:
    container_name: dm-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - WDS_SOCKET_HOST=127.0.0.1
      - NODE_ENV=development
  nginx:
    volumes:
        - ./nginx/templates/dev:/etc/nginx/templates