version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=${FRONTEND_PORT:-3000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - WDS_SOCKET_HOST=127.0.0.1
      - NODE_ENV=development
  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - ${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}
      - ${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
    depends_on:
      - frontend
    restart: always
