version: "3.8"

services:
  backend:
    container_name: dm-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080

  frontend:
    container_name: dm-frontend
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - REACT_APP_DOMAIN_NAME=${DOMAIN_NAME:-http://127.0.0.1}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-8080}
